[package]
name = "ros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
getch = "0.3.1"
simsearch = "0.2.3"
make_command = {path="./make_command"}
enable-ansi-support = "0.2.1"


